#!/usr/bin/env node
// Strips Push Notifications from the iOS native files generated by expo prebuild.
// expo-notifications always adds aps-environment + com.apple.Push; personal Apple
// Developer accounts don't support Push Notifications, so both must be removed.
// Run via: npm run prebuild:ios
// Remove this script when upgrading to a paid Apple Developer account.

const fs = require('fs');
const path = require('path');

const iosDir = path.join(__dirname, '..', 'ios');
const PROJECT = 'MedicSync';

// ── 1. Strip aps-environment from entitlements plist ─────────────────────────
const entPath = path.join(iosDir, PROJECT, `${PROJECT}.entitlements`);
if (!fs.existsSync(entPath)) {
  console.error('✗ Entitlements file not found:', entPath);
  process.exit(1);
}
const entBefore = fs.readFileSync(entPath, 'utf8');
const entAfter = entBefore.replace(/<key>aps-environment<\/key>[\s\S]*?<\/string>/g, '');
fs.writeFileSync(entPath, entAfter);
if (entBefore !== entAfter) {
  console.log('✓ Stripped aps-environment from', path.relative(process.cwd(), entPath));
} else {
  console.log('ℹ aps-environment was not present in entitlements');
}

// ── 2. Strip com.apple.Push block from project.pbxproj ───────────────────────
// Uses a line-by-line brace-depth tracker instead of regex so it is robust
// against any indentation or formatting style.
const pbxPath = path.join(iosDir, `${PROJECT}.xcodeproj`, 'project.pbxproj');
if (!fs.existsSync(pbxPath)) {
  console.error('✗ project.pbxproj not found:', pbxPath);
  process.exit(1);
}

const pbxLines = fs.readFileSync(pbxPath, 'utf8').split('\n');
const out = [];
let inBlock = false;
let depth = 0;
let blocksRemoved = 0;

for (const line of pbxLines) {
  if (!inBlock) {
    if (/"?com\.apple\.Push"?\s*=\s*\{/.test(line)) {
      inBlock = true;
      blocksRemoved++;
      depth = (line.match(/\{/g) ?? []).length - (line.match(/\}/g) ?? []).length;
      if (depth <= 0) inBlock = false; // single-line entry — already done
      continue; // skip the opening line
    }
    out.push(line);
  } else {
    depth += (line.match(/\{/g) ?? []).length - (line.match(/\}/g) ?? []).length;
    if (depth <= 0) inBlock = false; // closing brace of the block
    // skip every line inside the block (including the closing `};`)
  }
}

fs.writeFileSync(pbxPath, out.join('\n'));
if (blocksRemoved > 0) {
  console.log(`✓ Removed ${blocksRemoved} com.apple.Push block(s) from project.pbxproj`);
} else {
  console.log('ℹ com.apple.Push was not present in project.pbxproj');
}

console.log('Done.');
